import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Copy, FileText } from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { useData } from '@/contexts/DataContext';
import { useUserProfile } from '@/contexts/UserProfileContext';
import { OPPORTUNITY_CATEGORIES, type SavedTaxQuestion, type TaxOpportunityReviewItem, type TaxAdvisorProfile } from '@/hooks/useTaxAdvisor';

interface Props {
  questions: SavedTaxQuestion[];
  reviewItems: TaxOpportunityReviewItem[];
  profile: TaxAdvisorProfile | null;
}

export default function CPAPrepSummaryTab({ questions, reviewItems, profile }: Props) {
  const { facilities } = useData();
  const { profile: userProfile } = useUserProfile();

  const includedQuestions = questions.filter(q => q.include_in_summary);
  const reviewedAreas = reviewItems.filter(r => r.status !== 'not_started');

  const buildSummaryText = () => {
    const lines: string[] = [];
    lines.push('CPA PREP SUMMARY');
    lines.push('Generated by LocumOps — For discussion purposes only');
    lines.push('================================================');
    lines.push('');

    // Business context
    lines.push('BUSINESS CONTEXT');
    lines.push('----------------');
    if (userProfile?.company_name) lines.push(`Business Name: ${userProfile.company_name}`);
    if (profile?.entity_type) lines.push(`Entity Type: ${profile.entity_type.replace(/_/g, ' ')}`);
    if (userProfile?.profession) lines.push(`Profession: ${userProfile.profession}`);
    if (facilities?.length) {
      lines.push(`Facilities Worked: ${facilities.length}`);
      const states = new Set(facilities.map(f => {
        const parts = f.address?.split(',');
        return parts?.[parts.length - 1]?.trim()?.split(' ')?.[0];
      }).filter(Boolean));
      if (states.size > 0) lines.push(`States: ${[...states].join(', ')}`);
    }
    lines.push('');

    // Planning profile
    if (profile) {
      lines.push('PLANNING PROFILE');
      lines.push('-----------------');
      if (profile.travels_for_ce) lines.push('• Travels for CE');
      if (profile.uses_personal_vehicle) lines.push('• Uses personal vehicle for work');
      if (profile.multi_state_work) lines.push('• Works in multiple states');
      if (profile.pays_own_subscriptions) lines.push('• Pays own subscriptions/memberships');
      if (profile.retirement_planning_interest) lines.push('• Interested in retirement planning');
      if (profile.combines_business_personal_travel) lines.push('• Combines business and personal travel');
      if (profile.buys_supplies_equipment) lines.push('• Buys own supplies/equipment');
      lines.push('');
    }

    // Reviewed areas
    if (reviewedAreas.length > 0) {
      lines.push('REVIEWED PLANNING AREAS');
      lines.push('------------------------');
      reviewedAreas.forEach(r => {
        const cat = OPPORTUNITY_CATEGORIES.find(c => c.key === r.category);
        lines.push(`• ${cat?.label || r.category} — ${r.status.replace(/_/g, ' ')}`);
        if (r.notes) lines.push(`  Notes: ${r.notes}`);
      });
      lines.push('');
    }

    // Questions
    if (includedQuestions.length > 0) {
      lines.push('QUESTIONS FOR CPA');
      lines.push('------------------');
      includedQuestions.forEach((q, i) => {
        lines.push(`${i + 1}. ${q.question_text}`);
        lines.push(`   Topic: ${q.topic.replace(/_/g, ' ')}`);
      });
      lines.push('');
    }

    lines.push('================================================');
    lines.push('This summary is for educational and planning support only.');
    lines.push('LocumOps does not provide tax, legal, or financial advice.');

    return lines.join('\n');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(buildSummaryText());
    toast({ title: 'Summary copied to clipboard' });
  };

  return (
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground">
        Export the questions and topics you want to review with your CPA.
      </p>

      <div className="flex gap-2">
        <Button onClick={handleCopy} variant="outline">
          <Copy className="h-4 w-4 mr-2" /> Copy as Text
        </Button>
      </div>

      {/* Preview */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <FileText className="h-5 w-5 text-primary" />
            CPA Prep Summary Preview
          </CardTitle>
          <CardDescription>This is what will be exported. Toggle questions on/off in the My CPA Questions tab.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            {/* Context */}
            <div>
              <h4 className="font-semibold text-sm mb-2">Business Context</h4>
              <div className="text-sm text-muted-foreground space-y-1">
                {userProfile?.company_name && <p>Business: {userProfile.company_name}</p>}
                {profile?.entity_type && <p>Entity: {profile.entity_type.replace(/_/g, ' ')}</p>}
                {facilities && <p>Facilities: {facilities.length}</p>}
              </div>
            </div>

            {/* Reviewed areas */}
            {reviewedAreas.length > 0 && (
              <div>
                <h4 className="font-semibold text-sm mb-2">Reviewed Areas ({reviewedAreas.length})</h4>
                <div className="space-y-1">
                  {reviewedAreas.map(r => {
                    const cat = OPPORTUNITY_CATEGORIES.find(c => c.key === r.category);
                    return (
                      <p key={r.id} className="text-sm text-muted-foreground">
                        • {cat?.label} — <span className="capitalize">{r.status.replace(/_/g, ' ')}</span>
                      </p>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Questions */}
            {includedQuestions.length > 0 ? (
              <div>
                <h4 className="font-semibold text-sm mb-2">Questions for CPA ({includedQuestions.length})</h4>
                <ol className="list-decimal list-inside space-y-1">
                  {includedQuestions.map(q => (
                    <li key={q.id} className="text-sm text-muted-foreground">{q.question_text}</li>
                  ))}
                </ol>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">No questions selected for summary. Add or enable questions in the My CPA Questions tab.</p>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
